### ISSUE TITLE
有考虑新增评论功能不

### ISSUE THREAD

**Issue by Tokoy** [austin2035/astro-air-blog#14]
博客很轻量，孩子很喜欢！按文档教程已经成功把自己的博客部署到Vercel上了，也新增了Vercel的访问记录，如果可以新增评论的功能那就更好了，网上也有免费的数据库https://www.mongodb.com/cloud，只是提个小建议~

**Comment by austin2035** [comment]
有考虑，我将会有计划的增加评论功能。谢谢你的建议，我觉得有必要。
