### ISSUE TITLE
markdown 文档中使用 ”>" 引用，页面样式不生效

### ISSUE THREAD

**Issue by suwia** [austin2035/astro-air-blog#15]
如题，在示例文章 “talk-golang-slice.md” 中第 118 ~ 120行
![image](https://user-images.githubusercontent.com/41603348/225184903-af0a72ba-3a0f-42b3-8976-f00e3b95dbe4.png)
页面效果：
![image](https://user-images.githubusercontent.com/41603348/225185033-e42ed908-0357-47f6-8284-077ed4cd4702.png)
期望效果：

**Comment by austin2035** [comment]
感谢你的反馈，我将会考虑增加引用样式，以提升使用体验。
