### ISSUE TITLE
archive能否添加全部tag

### ISSUE THREAD

**Issue by miRemid** [austin2035/astro-air-blog#2]
阅读全部文章只能列出archive.astro里面指定的tag，能否改成所有tag？或者有没有别的方法看到真正所有的文章？

**Comment by miRemid** [comment]
谢谢回复，暂时使用第一种方法了

**Comment by tqgx** [comment]
> ```astro
> ```astro
> const tags = [...new Set(allPosts.map((post) => post.frontmatter.tags).flat())];
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

感謝，這個方法很有效！
