### ISSUE TITLE
调整文章内图片的尺寸？

### ISSUE THREAD

**Issue by Xmaspro** [austin2035/astro-air-blog#24]
在文章里是否可以手动调整图片的尺寸？

谢谢。

**Comment by austin2035** [comment]
可以，在说明文档中写过了：

> 有三种图片显示模式: wide, big, inline. 当你编写 mark 文件的时候可以指定 wide 或 big 或 inline 到你的图片 alt 属性中, 比如这样:

```
![alt content|wide](a.png)
```
分割符号是|,默认的模式为 big.
