### ISSUE TITLE
RSS时间倒序

### ISSUE THREAD

**Issue by Loongphy** [austin2035/astro-air-blog#25]

**Comment by Loongphy** [comment]
考虑使用 `Content Collections` 组织管理 `.md` 文件吗

**Comment by austin2035** [comment]
稍微研究了一下，没有仔细研究。
可能暂时还不太需要？我不是很确定。如果有必要，我可以加上。但现阶段看来貌似不需要。
另外时间倒序已经被 [PR26](https://github.com/austin2035/astro-air-blog/pull/26) 修复。
感谢你的建议。

**Comment by lanceliao** [comment]
抱歉，https://github.com/austin2035/astro-air-blog/pull/26 是修复 tags 页面乱序的问题，我另外提交了一个修复 https://github.com/austin2035/astro-air-blog/pull/27 来解决rss feed顺序的问题
