### ISSUE TITLE
代码块格式是否可以更改

### ISSUE THREAD

**Issue by xtR0d666** [austin2035/astro-air-blog#4]
首先非常感谢您详细的教程让一个小白也搭建了自己的博客网站。想请问一下有什么办法可以更改高亮代码块的格式如字体、黑白吗？

**Comment by austin2035** [comment]
需要通过 CSS 来修改代码块的样式。比如 code 标签下的样式，和 pre 标签下的样式。
然后配合 font-family 的属性来设置字体，黑白的话其实属于代码高亮。
代码高亮我使用的 hljs.js 来实现，可以参考官方文档来进一步了解。
