### ISSUE TITLE
大佬，您好，我是一名开发小白，想要请教您 几个问题。

### ISSUE THREAD

**Issue by ChiaMeow** [austin2035/astro-air-blog#40]
**一、请问如何把归档文章做成带封面的样式**
<img width="821" alt="image" src="https://github.com/austin2035/astro-air-blog/assets/130277385/7a6e692f-8f93-4f0e-bce3-518c890eb734">
比如这种：
<img width="863" alt="image" src="https://github.com/austin2035/astro-air-blog/assets/130277385/60739258-06cc-4056-ace9-f0ea033524de">

**二、请问为什么我上传的文章，前五张图片都有分隔线隔开，后面的图片之间就没有分隔线了**
<img width="934" alt="image" src="https://github.com/austin2035/astro-air-blog/assets/130277385/853ce0ac-4382-4b2a-96f0-389aebbfb717">
这是我编辑的Markdown文件：
<img width="464" alt="image" src="https://github.com/austin2035/astro-air-blog/assets/130277385/e57af81d-09fb-4207-840e-150291a18059">

**三、请问如何能把网页上的导航换成logo，或者icon+文字的样式**
<img width="251" alt="image" src="https://github.com/austin2035/astro-air-blog/assets/130277385/adcde74f-405f-4192-a2e4-efafb05422a9">
比如上图，把Wayne‘s Blog换成我自己的Logo

**四、请问更换网站的字体应该如何操作**

我的博客：https://www.xiiiao.love/
Github仓库：https://github.com/ChiaMeow/Blog/tree/main

不好意思，问题可能有点多，而且比较初级，让您见笑了。
但确实是从来没有接触过开发，完全不懂代码，全都是网上找教程照搬，连Astro的官方文档都看得吃力。
所以才会厚着脸皮来请教您。
也许会打扰到您，浪费您宝贵的时间。
但还是希望您不吝赐教。
万分感谢！

**Comment by ChiaMeow** [comment]
不好意思，上面有的文字和图片没有空行隔开，也许会让您看得吃力，抱歉。

**Comment by austin2035** [comment]
问题一：需要有前端开发基础，才可以改动，靠教程是改不成的。
问题二：可能是我代码写的问题，有一个重构 HTML结构的算法，可能写的不是特别的完善，导致了这个小问题。有时候，你可能需要把 Markdown 文件格式化一下就不会有排版和样式问题了，或者尝试在图片上下文加入换行和问题。
问题三：同问题一。
问题四：需要懂前端基础部分的 CSS 部分。具体来说是修改所有 font-family 属性。

总结，这是我基于 Astro 开发的博客，网络上流行度不够高。所以资料会比较少，其定位是给开发人员使用。
同时，我不建议再折腾了，博客的初衷是内容的创作和分享。

**Comment by ChiaMeow** [comment]
好的，非常感谢您的回复，祝您生活愉快！

发自我的 iPhone

在 2023年5月27日，09:39，Austin Li ***@***.***> 写道：

﻿

问题一：需要有前端开发基础，才可以改动，靠教程是改不成的。
问题二：可能是我代码写的问题，有一个重构 HTML结构的算法，可能写的不是特别的完善，导致了这个小问题。有时候，你可能需要把 Markdown 文件格式化一下就不会有排版和样式问题了，或者尝试在图片上下文加入换行和问题。
问题三：同问题一。
问题四：需要懂前端基础部分的 CSS 部分。具体来说是修改所有 font-family 属性。

总结，这是我基于 Astro 开发的博客，网络上流行度不够高。所以资料会比较少，其定位是给开发人员使用。
同时，我不建议再折腾了，博客的初衷是内容的创作和分享。
