### ISSUE TITLE
请答疑：文章内超链接如何实现在新页签打开？

### ISSUE THREAD

**Issue by chinesehuazhou** [austin2035/astro-air-blog#41]
博客文章中有文字超链接，目前点击后是在当前页签打开的。如何实现在新页签打开呢？

我前端小白，虽然知道是在 MarkdownPost.astro 渲染文章，但正文内容似乎是直接通过 slot 插入的？

如何比较好实现题目的诉求呢？

**Comment by austin2035** [comment]
一般是通过 a标签的 target  属性来实现，当值为 _blank 的时候，可以实现你说的效果。具体而言，想在生成的文章中实现效果可能需要修改 重构 HTML 的代码部分。这个我会留意一下，加入 TODO列表。
谢谢你的反馈。

**Comment by chinesehuazhou** [comment]
我已经找到了实现的方式，贴在这里，以便有需要的同学查看

在 initPost.js

找到加载的部分，添加（原文件已被我重构，看个大概吧）

document.querySelectorAll('a').forEach((el) => {
      el.setAttribute('target', '_blank');
    });

![image](https://github.com/austin2035/astro-air-blog/assets/4251458/e6496dea-3ded-4994-aa90-0be35ee7cef2)
