### ISSUE TITLE
issue: duplicated <style> tag

### ISSUE THREAD

**Issue by floyd-li** [austin2035/astro-air-blog#5]
lots of duplicated <style> tag with same content

<img width="564" alt="image" src="https://user-images.githubusercontent.com/16473062/223143614-97dfb344-4314-473c-b38e-81ac42cbfb60.png">

**Comment by austin2035** [comment]
应该是不一样的，每个图片都会生成一个对应的 style 标签。区别在于 class name 中的 md5值。
