### ISSUE TITLE
博客文章无法插入图片

### ISSUE THREAD

**Issue by xtR0d666** [austin2035/astro-air-blog#7]
我将图片资源存在/public/preview 目录下，在博客文章的markdown中想要插入图片，但是文章中却不能显示图片。

**Comment by austin2035** [comment]
你插入的路径是多少。
应该是
```markdown
![alt](/preview/xxx.png)
```
建议使用靠谱的外链网站，另外图片记得备份。

**Comment by xtR0d666** [comment]
我的路径就是这么填写的，但是还是无法展示出图片

**Comment by chenxushan** [comment]
> 我将图片资源存在/public/preview 目录下，在博客文章的markdown中想要插入图片，但是文章中却不能显示图片。

不需要加/public，我看了官网，只需要/preview就可以了，我之前也是加了public，发现加载不了，查看官网文档，有代码demo，不需要/public
