### ISSUE TITLE
能否添加开源协议？

### ISSUE THREAD

**Issue by floyd-li** [austin2035/astro-air-blog#8]
作者您好，之前看到在V站上看到您准备选一个自由一点的开源协议，不知是否可以附在repo中？
我原本准备将移植的主题提交到Hugo官方主题库中，因为是基于您的主题进行移植的，而这边没有添加开源的协议导致无法被合入

https://github.com/gohugoio/hugoThemesSiteBuilder/pull/275#issuecomment-1459952272

**Comment by austin2035** [comment]
OK 我明天加入
